lang: rust
script:
  - git config --global user.email "hekinami@amiunique.net"
  - git config --global user.name "Zou Bibo"
  - pwd
  - echo "deploy into github"
  - git clone https://${ACCESS_TOKEN}@github.com/hekinami/amiunique.net.git
  - rsync -av --delete --exclude=.git --exclude=CNAME _site/ amiunique.net
  - cd amiunique.net
  - git add .
  - git commit -m "test"
  - git push
  - cd ..
  - echo "deploy into gitlab"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - rm -rf ~/.ssh/config
  - echo "Host gitlab.com" > ~/.ssh/config
  - echo "User git" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "IdentityFile ~/id_rsa" >> ~/.ssh/config
  - echo "IdentitiesOnly yes" >> ~/.ssh/config
  - echo -e ${TENCENT_PRIV_KEY} > ~/id_rsa
  - chmod 600 ~/id_rsa
  - git clone git@gitlab.com:hekinami/hekinami.git gitlab
  - rsync -av --delete --exclude=.git --exclude=CNAME _site/ gitlab/public
  - cd gitlab
  - cp public/.gitlab-ci.yml .
  - git add .
  - git commit -m "test"
  - git push
  
