lang: rust
script:
  - git config --global user.email "hekinami@amiunique.net"
  - git config --global user.name "Zou Bibo"
  - pwd
  - COMMIT_MSG=$(git log -1 --pretty=%s)
  - echo "Deploy into gitlab"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - rm -rf ~/.ssh/config
  - echo "Host gitlab.com" > ~/.ssh/config
  - echo "User git" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "IdentityFile ~/id_rsa" >> ~/.ssh/config
  - echo "IdentitiesOnly yes" >> ~/.ssh/config
  - echo -e ${GITLAB_PRIV_KEY} > ~/id_rsa
  - chmod 600 ~/id_rsa
  - git clone git@gitlab.com:hekinami/hekinami.git gitlab
  - rsync -av --delete --exclude=.git --exclude=CNAME _site/ gitlab/public
  - cp .gitlab-ci.yml gitlab
  - cd gitlab
  - git add .
  - git commit -m "${COMMIT_MSG}"
  - git push
  
